### ISSUE TITLE
Describe how to setup environment

### ISSUE THREAD

**Issue by apletnev** [SergeyKhval/ossu-client#7]
After execution **grunt serve** command returns next error:
 
> ➜  ossu-client git:(dev) grunt serve
> Running "serve" task
> 
> Running "clean:server" (clean) task
> >> 0 paths cleaned.
> 
> Running "wiredep:app" (wiredep) task
> 
> Running "wiredep:test" (wiredep) task
> 
> Running "wiredep:sass" (wiredep) task
> 
> Running "concurrent:server" (concurrent) task
>     Warning: Running "compass:server" (compass) task
>     Warning: not found: compass Use --force to continue.
> 
>     Aborted due to warnings.
> 
> 
>     Execution Time (2016-03-24 15:13:04 UTC)
>     loading tasks   4ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 33%
>     compass:server  7ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 58%
>     Total 12ms Use --force to continue.
> 
>         Aborted due to warnings.
> 
> 
> Execution Time (2016-03-24 15:13:02 UTC)
> wiredep:app        40ms  ▇▇▇▇▇ 2%
> concurrent:server  2.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
> Total 2.2s
>

**Comment by SergeyKhval** [comment]
@apletnev you need to have Ruby, Sass and Compass installed in order to run this project. Head [over here](https://github.com/gruntjs/grunt-contrib-compass#compass-task) and follow the instructions.

After you have environment set up, go to `\bower_components\bootstrap-material-design\sass\_import-bs-sass.scss` and comment everything out in that file, save and try run `grunt serve again`.
